modLoader = "javafml"
loaderVersion = "[4.0.24,)"
issueTrackerURL = "https://github.com/anabsolutesloth/cobblemonreleaserewards/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = [
    "${mod_authors}"
]
description = '''${mod_description}'''
# logo file optional
logoFile = "assets/releaserewards/${mod_id}_icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${loader_version},)"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${forge_kotlin_version},)"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"

[[dependencies.${mod_id}]]
modId = "cobblemon"
mandatory = true
versionRange = "[${cobblemon_version},)"
